### ISSUE TITLE
Bug: Unable to connect to

### ISSUE THREAD

**Issue by daniel-wtd** [flathub/org.gnome.Notes#13]
Hi,

not sure if this is flatpak or notes releated. Since the last update, I am no longer able to connect to my Nextcloud account, which was working just some weeks ago (it was even better after the notes 40 update).

Now I am getting:

```
$ flatpak run org.gnome.Notes 
Gtk-Message: 08:34:14.400: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:34:14.401: Failed to load module "canberra-gtk-module"
** Message: 08:34:14.468: Loading account account_1616230551_0

** (bijiben:2): WARNING **: 08:34:14.808: On Client Connected : Unable to connect to “Personal”: org.freedesktop.DBus.Error.ServiceUnknown
```

In case, I can provide anything to support here, please feel free to give me a ping.

**Comment by igaldino** [comment]
Hi @daniel-wtd thanks for your bug report.

I already have an issue opened upstream: https://gitlab.gnome.org/GNOME/gnome-notes/-/issues/171 but I'm not sure if it's related to flatpak or Notes itself. Anyway, I'd like to keep the history there, so I'll close this one.

Would you please report there which Nextcloud provider you're using? So I can check the API version they are using and advice accordingly, because in my tests (both flatpak and not flatpak versions) I was able to access my Nextcloud account with no issue.

Thanks again.

**Comment by daniel-wtd** [comment]
I am not on a provider but having a setup like this:

- Nextcloud 20.0.x
- gnome-online.accounts-3.39 (used to connect to nextcloud)
- Fedora 34

I will have another look in a vm / fresh setup and update the other ticket, if I can see anything else. Since it was already working with gnome notes 40, it can also be something in Fedora. :/
